import { Guest, Party, Table, Expense, Milestone, SongRequest, VenueSourcingResult } from './types';

export const initialParties: Party[] = [
  {
    id: 'party-1',
    primary_guest_name: 'Ông Bà Ngoại & Bác Hai (Nguyen Family)',
    invitation_code: 'VIP-NGUYEN-01',
    total_invited: 4,
    contact_email: 'nguyen.family@example.com',
    contact_phone: '+1 (714) 555-0101',
    notes: 'Elder VIP table seating stage-front',
    created_at: '2026-08-01T10:00:00Z'
  },
  {
    id: 'party-2',
    primary_guest_name: 'Roberto & Maria Rossi',
    invitation_code: 'VIP-ROSSI-02',
    total_invited: 3,
    contact_email: 'roberto.rossi@example.com',
    contact_phone: '+1 (714) 555-0102',
    notes: 'Alfredo parents and sister',
    created_at: '2026-08-01T10:00:00Z'
  },
  {
    id: 'party-3',
    primary_guest_name: 'Cô Sáu & Chú Bảy Tran',
    invitation_code: 'REL-TRAN-03',
    total_invited: 4,
    contact_email: 'tran.family@example.com',
    contact_phone: '+1 (714) 555-0103',
    notes: 'Extended relatives',
    created_at: '2026-08-05T10:00:00Z'
  },
  {
    id: 'party-4',
    primary_guest_name: 'Kevin Vo & Tram Le',
    invitation_code: 'FR-VO-04',
    total_invited: 2,
    contact_email: 'kevin.vo@example.com',
    contact_phone: '+1 (714) 555-0104',
    notes: 'Close friends',
    created_at: '2026-08-10T10:00:00Z'
  },
  {
    id: 'party-5',
    primary_guest_name: 'David Miller',
    invitation_code: 'FR-MILLER-05',
    total_invited: 2,
    contact_email: 'david.miller@example.com',
    contact_phone: '+1 (714) 555-0105',
    notes: 'Coworker',
    created_at: '2026-08-12T10:00:00Z'
  },
  {
    id: 'party-6',
    primary_guest_name: 'Carlos & Elena Gomez',
    invitation_code: 'FR-GOMEZ-06',
    total_invited: 2,
    contact_email: 'carlos.g@example.com',
    contact_phone: '+1 (714) 555-0106',
    notes: 'Sports league crew',
    created_at: '2026-08-15T10:00:00Z'
  },
  {
    id: 'party-7',
    primary_guest_name: 'Anh Tuấn & Chị Mai Le',
    invitation_code: 'REL-LE-07',
    total_invited: 3,
    contact_email: 'tuan.le@example.com',
    contact_phone: '+1 (714) 555-0107',
    notes: 'Cousins',
    created_at: '2026-08-18T10:00:00Z'
  },
  {
    id: 'party-8',
    primary_guest_name: 'Marcus & Chloe Sterling',
    invitation_code: 'FR-STERLING-08',
    total_invited: 2,
    contact_email: 'marcus.s@example.com',
    contact_phone: '+1 (714) 555-0108',
    notes: 'Pending RSVP followup needed',
    created_at: '2026-08-20T10:00:00Z'
  }
];

export const initialTables: Table[] = [
  {
    id: 'table-1',
    table_number: 1,
    name: 'Bàn 1: Trưởng Bối & VIP Family (Stage-Front Left)',
    capacity: 10,
    hierarchy_tag: 'vip_family',
    stage_position: 'stage_front_left'
  },
  {
    id: 'table-2',
    table_number: 2,
    name: 'Bàn 2: Rossi Family & Godparents (Stage-Front Right)',
    capacity: 10,
    hierarchy_tag: 'vip_family',
    stage_position: 'stage_front_right'
  },
  {
    id: 'table-3',
    table_number: 3,
    name: 'Bàn 3: Họ Hàng Nhà Gái (Cô, Dì, Chú, Bác)',
    capacity: 10,
    hierarchy_tag: 'extended_relatives',
    stage_position: 'center'
  },
  {
    id: 'table-4',
    table_number: 4,
    name: 'Bàn 4: Họ Hàng & Anh Chị Em Họ (Cousins & Relatives)',
    capacity: 10,
    hierarchy_tag: 'extended_relatives',
    stage_position: 'center'
  },
  {
    id: 'table-5',
    table_number: 5,
    name: 'Bàn 5: Tech & Creative Friends (Near Bar)',
    capacity: 10,
    hierarchy_tag: 'friends_bar',
    stage_position: 'near_bar'
  },
  {
    id: 'table-6',
    table_number: 6,
    name: 'Bàn 6: College & High School Alumni Crew',
    capacity: 10,
    hierarchy_tag: 'friends_bar',
    stage_position: 'near_bar'
  },
  {
    id: 'table-7',
    table_number: 7,
    name: 'Bàn 7: Bowling & Sports League Teammates',
    capacity: 10,
    hierarchy_tag: 'friends_bar',
    stage_position: 'back'
  },
  {
    id: 'table-8',
    table_number: 8,
    name: 'Bàn 8: Buffer & Open Banquet Table',
    capacity: 10,
    hierarchy_tag: 'general',
    stage_position: 'back'
  }
];

export const initialGuests: Guest[] = [
  // Table 1 (VIP Stage Front Left)
  {
    id: 'guest-1',
    party_id: 'party-1',
    first_name: 'Bà Ngoại (Grandmother)',
    last_name: 'Nguyen',
    email: 'grandmother.nguyen@example.com',
    phone: '+1 (714) 555-0101',
    rsvp_status: 'attending',
    headcount: 1,
    dietary_restrictions: ['Vegetarian', 'No Shellfish'],
    dietary_notes: 'Soft texture foods, vegetarian options preferred',
    song_request: 'Sài Gòn Đẹp Lắm',
    table_id: 'table-1',
    table_seat_number: 1,
    is_primary_contact: true,
    relationship_tag: 'vip_family',
    created_at: '2026-08-01T10:00:00Z',
    updated_at: '2026-08-01T10:00:00Z'
  },
  {
    id: 'guest-2',
    party_id: 'party-1',
    first_name: 'Bác Hai (Uncle Hai)',
    last_name: 'Nguyen',
    rsvp_status: 'attending',
    headcount: 1,
    dietary_restrictions: [],
    table_id: 'table-1',
    table_seat_number: 2,
    is_primary_contact: false,
    relationship_tag: 'vip_family',
    created_at: '2026-08-01T10:00:00Z',
    updated_at: '2026-08-01T10:00:00Z'
  },
  {
    id: 'guest-3',
    party_id: 'party-1',
    first_name: 'Bác Gái (Aunt Lan)',
    last_name: 'Nguyen',
    rsvp_status: 'attending',
    headcount: 1,
    dietary_restrictions: ['Peanut Allergy'],
    dietary_notes: 'Severe peanut allergy',
    table_id: 'table-1',
    table_seat_number: 3,
    is_primary_contact: false,
    relationship_tag: 'vip_family',
    created_at: '2026-08-01T10:00:00Z',
    updated_at: '2026-08-01T10:00:00Z'
  },
  {
    id: 'guest-4',
    party_id: 'party-1',
    first_name: 'Mẹ Cô Dâu (Trang Mom)',
    last_name: 'Tran',
    rsvp_status: 'attending',
    headcount: 1,
    dietary_restrictions: [],
    song_request: '60 Năm Cuộc Đời',
    table_id: 'table-1',
    table_seat_number: 4,
    is_primary_contact: false,
    relationship_tag: 'vip_family',
    created_at: '2026-08-01T10:00:00Z',
    updated_at: '2026-08-01T10:00:00Z'
  },

  // Table 2 (VIP Rossi Family)
  {
    id: 'guest-5',
    party_id: 'party-2',
    first_name: 'Roberto',
    last_name: 'Rossi',
    email: 'roberto.rossi@example.com',
    phone: '+1 (714) 555-0102',
    rsvp_status: 'attending',
    headcount: 1,
    dietary_restrictions: [],
    song_request: 'That’s Amore - Dean Martin',
    table_id: 'table-2',
    table_seat_number: 1,
    is_primary_contact: true,
    relationship_tag: 'vip_family',
    created_at: '2026-08-01T10:00:00Z',
    updated_at: '2026-08-01T10:00:00Z'
  },
  {
    id: 'guest-6',
    party_id: 'party-2',
    first_name: 'Maria',
    last_name: 'Rossi',
    rsvp_status: 'attending',
    headcount: 1,
    dietary_restrictions: ['Gluten-Free'],
    dietary_notes: 'Celiac friendly options',
    table_id: 'table-2',
    table_seat_number: 2,
    is_primary_contact: false,
    relationship_tag: 'vip_family',
    created_at: '2026-08-01T10:00:00Z',
    updated_at: '2026-08-01T10:00:00Z'
  },
  {
    id: 'guest-7',
    party_id: 'party-2',
    first_name: 'Giulia',
    last_name: 'Rossi',
    rsvp_status: 'attending',
    headcount: 1,
    dietary_restrictions: [],
    song_request: 'Dancing Queen - ABBA',
    table_id: 'table-2',
    table_seat_number: 3,
    is_primary_contact: false,
    relationship_tag: 'vip_family',
    created_at: '2026-08-01T10:00:00Z',
    updated_at: '2026-08-01T10:00:00Z'
  },

  // Table 3 (Extended Relatives)
  {
    id: 'guest-8',
    party_id: 'party-3',
    first_name: 'Cô Sáu',
    last_name: 'Tran',
    email: 'tran.family@example.com',
    phone: '+1 (714) 555-0103',
    rsvp_status: 'attending',
    headcount: 1,
    dietary_restrictions: [],
    song_request: 'Bài Ca Kỷ Niệm',
    table_id: 'table-3',
    table_seat_number: 1,
    is_primary_contact: true,
    relationship_tag: 'extended_relatives',
    created_at: '2026-08-05T10:00:00Z',
    updated_at: '2026-08-05T10:00:00Z'
  },
  {
    id: 'guest-9',
    party_id: 'party-3',
    first_name: 'Chú Bảy',
    last_name: 'Tran',
    rsvp_status: 'attending',
    headcount: 1,
    dietary_restrictions: [],
    table_id: 'table-3',
    table_seat_number: 2,
    is_primary_contact: false,
    relationship_tag: 'extended_relatives',
    created_at: '2026-08-05T10:00:00Z',
    updated_at: '2026-08-05T10:00:00Z'
  },
  {
    id: 'guest-10',
    party_id: 'party-3',
    first_name: 'Anh Khoa',
    last_name: 'Tran',
    rsvp_status: 'attending',
    headcount: 1,
    dietary_restrictions: ['Shellfish Allergy'],
    dietary_notes: 'No shrimp or crab',
    table_id: 'table-3',
    table_seat_number: 3,
    is_primary_contact: false,
    relationship_tag: 'extended_relatives',
    created_at: '2026-08-05T10:00:00Z',
    updated_at: '2026-08-05T10:00:00Z'
  },
  {
    id: 'guest-11',
    party_id: 'party-3',
    first_name: 'Chị Vy',
    last_name: 'Tran',
    rsvp_status: 'attending',
    headcount: 1,
    dietary_restrictions: [],
    table_id: 'table-3',
    table_seat_number: 4,
    is_primary_contact: false,
    relationship_tag: 'extended_relatives',
    created_at: '2026-08-05T10:00:00Z',
    updated_at: '2026-08-05T10:00:00Z'
  },

  // Table 5 (Tech Friends near bar)
  {
    id: 'guest-12',
    party_id: 'party-4',
    first_name: 'Kevin',
    last_name: 'Vo',
    email: 'kevin.vo@example.com',
    phone: '+1 (714) 555-0104',
    rsvp_status: 'attending',
    headcount: 1,
    dietary_restrictions: [],
    song_request: 'September - Earth, Wind & Fire',
    table_id: 'table-5',
    table_seat_number: 1,
    is_primary_contact: true,
    relationship_tag: 'friends_bar',
    created_at: '2026-08-10T10:00:00Z',
    updated_at: '2026-08-10T10:00:00Z'
  },
  {
    id: 'guest-13',
    party_id: 'party-4',
    first_name: 'Tram',
    last_name: 'Le',
    rsvp_status: 'attending',
    headcount: 1,
    dietary_restrictions: ['Vegetarian'],
    dietary_notes: 'Vegetarian banquet dishes',
    table_id: 'table-5',
    table_seat_number: 2,
    is_primary_contact: false,
    relationship_tag: 'friends_bar',
    created_at: '2026-08-10T10:00:00Z',
    updated_at: '2026-08-10T10:00:00Z'
  },
  {
    id: 'guest-14',
    party_id: 'party-5',
    first_name: 'David',
    last_name: 'Miller',
    email: 'david.miller@example.com',
    phone: '+1 (714) 555-0105',
    rsvp_status: 'attending',
    headcount: 1,
    dietary_restrictions: ['Halal'],
    table_id: 'table-5',
    table_seat_number: 3,
    is_primary_contact: true,
    relationship_tag: 'friends_bar',
    created_at: '2026-08-12T10:00:00Z',
    updated_at: '2026-08-12T10:00:00Z'
  },

  // Table 7 (Sports League)
  {
    id: 'guest-15',
    party_id: 'party-6',
    first_name: 'Carlos',
    last_name: 'Gomez',
    email: 'carlos.g@example.com',
    phone: '+1 (714) 555-0106',
    rsvp_status: 'attending',
    headcount: 1,
    dietary_restrictions: [],
    song_request: 'Uptown Funk - Bruno Mars',
    table_id: 'table-7',
    table_seat_number: 1,
    is_primary_contact: true,
    relationship_tag: 'friends_bar',
    created_at: '2026-08-15T10:00:00Z',
    updated_at: '2026-08-15T10:00:00Z'
  },
  {
    id: 'guest-16',
    party_id: 'party-6',
    first_name: 'Elena',
    last_name: 'Gomez',
    rsvp_status: 'attending',
    headcount: 1,
    dietary_restrictions: [],
    table_id: 'table-7',
    table_seat_number: 2,
    is_primary_contact: false,
    relationship_tag: 'friends_bar',
    created_at: '2026-08-15T10:00:00Z',
    updated_at: '2026-08-15T10:00:00Z'
  },

  // Pending Guests (for Agent C chaser simulation)
  {
    id: 'guest-17',
    party_id: 'party-7',
    first_name: 'Anh Tuấn',
    last_name: 'Le',
    email: 'tuan.le@example.com',
    phone: '+1 (714) 555-0107',
    rsvp_status: 'pending',
    headcount: 1,
    dietary_restrictions: [],
    table_id: null,
    is_primary_contact: true,
    relationship_tag: 'extended_relatives',
    created_at: '2026-08-18T10:00:00Z',
    updated_at: '2026-08-18T10:00:00Z'
  },
  {
    id: 'guest-18',
    party_id: 'party-7',
    first_name: 'Chị Mai',
    last_name: 'Le',
    rsvp_status: 'pending',
    headcount: 1,
    dietary_restrictions: [],
    table_id: null,
    is_primary_contact: false,
    relationship_tag: 'extended_relatives',
    created_at: '2026-08-18T10:00:00Z',
    updated_at: '2026-08-18T10:00:00Z'
  },
  {
    id: 'guest-19',
    party_id: 'party-8',
    first_name: 'Marcus',
    last_name: 'Sterling',
    email: 'marcus.s@example.com',
    phone: '+1 (714) 555-0108',
    rsvp_status: 'pending',
    headcount: 1,
    dietary_restrictions: [],
    table_id: null,
    is_primary_contact: true,
    relationship_tag: 'friends_bar',
    created_at: '2026-08-20T10:00:00Z',
    updated_at: '2026-08-20T10:00:00Z'
  },
  {
    id: 'guest-20',
    party_id: 'party-8',
    first_name: 'Chloe',
    last_name: 'Sterling',
    rsvp_status: 'pending',
    headcount: 1,
    dietary_restrictions: [],
    table_id: null,
    is_primary_contact: false,
    relationship_tag: 'friends_bar',
    created_at: '2026-08-20T10:00:00Z',
    updated_at: '2026-08-20T10:00:00Z'
  },

  // Declined Guest
  {
    id: 'guest-21',
    party_id: 'party-declined',
    first_name: 'Richard',
    last_name: 'Hendricks',
    email: 'richard@piedpiper.test',
    phone: '+1 (714) 555-0199',
    rsvp_status: 'declined',
    headcount: 1,
    dietary_restrictions: [],
    notes: 'Traveling overseas for tech summit, sending warm blessings!',
    table_id: null,
    is_primary_contact: true,
    relationship_tag: 'friends_bar',
    created_at: '2026-08-22T10:00:00Z',
    updated_at: '2026-08-22T10:00:00Z'
  }
];

export const initialExpenses: Expense[] = [
  {
    id: 'exp-1',
    category: 'venue_banquet',
    vendor_name: 'Grand Harbor Restaurant',
    item_description: '8-Course Grand Asian Banquet (8 Tables + Dessert & Tea Service)',
    estimated_cost: 14500,
    actual_invoiced: 14500,
    deposit_paid: 5000,
    remaining_balance: 9500,
    payment_due_date: '2026-11-20',
    payment_status: 'pending',
    notes: 'Includes banquet staff, linens, audio, and tea service',
    created_at: '2026-08-01T10:00:00Z'
  },
  {
    id: 'exp-2',
    category: 'host_beverages_corkage',
    vendor_name: 'BevMo Wholesale & Grand Harbor Corkage',
    item_description: 'Couple-Supplied Bar: Hennessy XO (8 Bottles Chào Bàn), Macallan 12, Napa Cabernet, Prosecco & Bartender Service',
    estimated_cost: 4200,
    actual_invoiced: 4200,
    deposit_paid: 1500,
    remaining_balance: 2700,
    payment_due_date: '2026-11-15',
    payment_status: 'pending',
    notes: 'Couple provides wholesale spirits; venue provides glassware, ice, mixers & licensed pouring',
    created_at: '2026-08-05T10:00:00Z'
  },
  {
    id: 'exp-3',
    category: 'attire',
    vendor_name: 'Áo Dài Ninh Khương & Indochine Tailors',
    item_description: 'Custom Silk Embroidered Couple Áo Dài + Western Tuxedo & Evening Gown',
    estimated_cost: 2800,
    actual_invoiced: 2800,
    deposit_paid: 2800,
    remaining_balance: 0,
    payment_due_date: '2026-08-15',
    payment_status: 'paid',
    notes: 'Paid in full upon final custom fitting',
    created_at: '2026-08-01T10:00:00Z'
  },
  {
    id: 'exp-4',
    category: 'stage_av_dj',
    vendor_name: 'Saigon Nights AV & DJ Danny K',
    item_description: 'Bilingual Vietnamese/English MC, DJ Sound System, Wireless Mics & Ambient Uplighting',
    estimated_cost: 3600,
    actual_invoiced: 3600,
    deposit_paid: 1200,
    remaining_balance: 2400,
    payment_due_date: '2026-10-30',
    payment_status: 'pending',
    notes: 'Includes program coordination and dance lighting package',
    created_at: '2026-08-08T10:00:00Z'
  },
  {
    id: 'exp-5',
    category: 'decor_floral',
    vendor_name: 'Lotus & Pearl Floral Design',
    item_description: 'Traditional Red & Gold Welcome Backdrop, 8 Table Floral Centerpieces & Sweetheart Table',
    estimated_cost: 4500,
    actual_invoiced: 4500,
    deposit_paid: 2000,
    remaining_balance: 2500,
    payment_due_date: '2026-11-01',
    payment_status: 'pending',
    notes: 'Fresh orchids, red roses, and custom neon name sign',
    created_at: '2026-08-10T10:00:00Z'
  },
  {
    id: 'exp-6',
    category: 'photography_video',
    vendor_name: 'Lumière Cinema & Photography',
    item_description: '8 Hours Dual Shooter Coverage, Highlight Film, Banquet Toasting Recap',
    estimated_cost: 3800,
    actual_invoiced: 3800,
    deposit_paid: 1500,
    remaining_balance: 2300,
    payment_due_date: '2026-09-12',
    payment_status: 'pending',
    notes: 'Final balance due on wedding night',
    created_at: '2026-08-12T10:00:00Z'
  },
  {
    id: 'exp-7',
    category: 'gifts_favors',
    vendor_name: 'Hỷ Sự Silk Favors & Tea Gifts',
    item_description: 'Traditional Red Bao Lì Xì, Jasmine Tea Favors & Personalized Gold Chopsticks for 80 Guests',
    estimated_cost: 1200,
    actual_invoiced: 1200,
    deposit_paid: 1200,
    remaining_balance: 0,
    payment_due_date: '2026-08-20',
    payment_status: 'paid',
    notes: 'Received and packaged',
    created_at: '2026-08-15T10:00:00Z'
  },
  {
    id: 'exp-8',
    category: 'misc',
    vendor_name: 'Contingency & Emergency Kit',
    item_description: 'Miscellaneous Tips, Printing of Menus & Table Cards, Emergency Sewing Kit',
    estimated_cost: 1500,
    actual_invoiced: 800,
    deposit_paid: 0,
    remaining_balance: 800,
    payment_due_date: '2026-09-08',
    payment_status: 'pending',
    notes: 'Buffer reserve for day-of coordination',
    created_at: '2026-08-25T10:00:00Z'
  }
];

export const initialMilestones: Milestone[] = [
  {
    id: 'ms-1',
    title_en: 'Finalize 8-Course Banquet Menu Tasting',
    title_vi: 'Duyệt Thử Vị & Khóa Thực Đơn 8 Món Yến Tiệc',
    category: 'venue',
    target_date: '2026-08-10',
    status: 'completed',
    priority: 'critical',
    assignee: 'Alfredo & Partner',
    cultural_notes: 'Tested lobster with ginger scallion and seafood soup with parents approval',
    updated_at: '2026-08-10T10:00:00Z'
  },
  {
    id: 'ms-2',
    title_en: 'Custom Silk Áo Dài Second Fitting',
    title_vi: 'Thử Áo Dài Lần 2 & Chỉnh Sửa Phom Dáng',
    category: 'attire',
    target_date: '2026-08-15',
    status: 'completed',
    priority: 'high',
    assignee: 'Alfredo & Partner',
    cultural_notes: 'Gold thread dragon and phoenix embroidery finalized',
    updated_at: '2026-08-15T10:00:00Z'
  },
  {
    id: 'ms-3',
    title_en: 'RSVP Cutoff & Automated Chaser Campaign',
    title_vi: 'Hạn Chót Xác Nhận RSVP & Kích Hoạt Hệ Thống Nhắc Hẹn',
    category: 'guest_rsvp',
    target_date: '2026-08-12',
    status: 'completed',
    priority: 'critical',
    assignee: 'Alfredo & Partner',
    cultural_notes: 'All outstanding parties get T-21 and T-7 SMS/Email nudges',
    updated_at: '2026-08-12T10:00:00Z'
  },
  {
    id: 'ms-4',
    title_en: 'Chào Bàn (Table Toasting) Strategy & Route Mapping',
    title_vi: 'Lập Kế Hoạch Đi Chào Từng Bàn Tiệc & Phân Công Người Dẫn Đường',
    category: 'ceremony',
    target_date: '2026-09-01',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Best Man / Groomsmen',
    cultural_notes: 'Assign groomsman/bridesmaid to hold Cognac tray, red envelope pouch, and guide couple from VIP 1 through 8',
    updated_at: '2026-08-30T10:00:00Z'
  },
  {
    id: 'ms-5',
    title_en: 'Host-Supplied Cognac & Wine Stock Delivery',
    title_vi: 'Giao Rượu Hennessy & Rượu Vang Đến Nhà Hàng Kiểm Đếm',
    category: 'beverage',
    target_date: '2026-09-05',
    status: 'pending',
    priority: 'high',
    assignee: 'Best Man / Groomsmen',
    cultural_notes: 'Verify 8 bottles of Hennessy XO for tables + bar stock with banquet manager',
    updated_at: '2026-08-30T10:00:00Z'
  },
  {
    id: 'ms-6',
    title_en: 'Final Headcount & Kitchen Dietary Matrix Lock',
    title_vi: 'Chốt Số Lượng Bàn 10 Người & Danh Sách Ăn Kiêng Cho Bếp Trưởng',
    category: 'logistics',
    target_date: '2026-09-07',
    status: 'pending',
    priority: 'critical',
    assignee: 'Alfredo & Partner',
    cultural_notes: 'Lock exact table count with Grand Harbor banquet manager (Table multiplier math)',
    updated_at: '2026-08-30T10:00:00Z'
  },
  {
    id: 'ms-7',
    title_en: 'Stage AV Rehearsal & Master DJ Song Cue Lock',
    title_vi: 'Tổng Duyệt Âm Thanh Ánh Sáng & Khóa Danh Sách Nhạc DJ',
    category: 'ceremony',
    target_date: '2026-09-10',
    status: 'pending',
    priority: 'medium',
    assignee: 'Maid of Honor / Bridesmaids',
    cultural_notes: 'Review bilingual MC script for grand entrance and toast transitions',
    updated_at: '2026-08-30T10:00:00Z'
  },
  {
    id: 'ms-8',
    title_en: 'The Wedding Celebration Night!',
    title_vi: 'Đêm Dạ Tiệc Cưới Chính Thức (12/09/2026)!',
    category: 'ceremony',
    target_date: '2026-09-12',
    status: 'pending',
    priority: 'critical',
    assignee: 'Alfredo & Partner',
    cultural_notes: 'Celebration, feast, Chào Bàn, dancing and memories!',
    updated_at: '2026-08-30T10:00:00Z'
  }
];

export const initialSongRequests: SongRequest[] = [
  {
    id: 'song-1',
    guest_name: 'Bà Ngoại Nguyen',
    song_title: 'Sài Gòn Đẹp Lắm',
    artist: 'Y Vân',
    genre: 'viet_bolero',
    notes: 'Classic feel-good song for welcome cocktail hour',
    status: 'queued',
    created_at: '2026-08-01T10:00:00Z'
  },
  {
    id: 'song-2',
    guest_name: 'Mẹ Cô Dâu (Trang Mom)',
    song_title: '60 Năm Cuộc Đời',
    artist: 'Y Vân',
    genre: 'vpop',
    notes: 'Great upbeat song for Chào Bàn table toasting',
    status: 'queued',
    created_at: '2026-08-01T10:00:00Z'
  },
  {
    id: 'song-3',
    guest_name: 'Roberto Rossi',
    song_title: 'That’s Amore',
    artist: 'Dean Martin',
    genre: '90s_2000s_classics',
    notes: 'Italian family celebration classic',
    status: 'queued',
    created_at: '2026-08-01T10:00:00Z'
  },
  {
    id: 'song-4',
    guest_name: 'Kevin Vo',
    song_title: 'September',
    artist: 'Earth, Wind & Fire',
    genre: 'edm_dance',
    notes: 'Guaranteed dance floor ignite!',
    status: 'queued',
    created_at: '2026-08-10T10:00:00Z'
  },
  {
    id: 'song-5',
    guest_name: 'Carlos Gomez',
    song_title: 'Uptown Funk',
    artist: 'Bruno Mars & Mark Ronson',
    genre: 'hiphop_rnb',
    notes: 'High energy party track',
    status: 'queued',
    created_at: '2026-08-15T10:00:00Z'
  }
];

export const initialSourcedVenues: VenueSourcingResult[] = [
  {
    id: 'venue-1',
    name: 'Grand Harbor Restaurant',
    location: 'Temple City, CA',
    max_capacity_guests: 350,
    ten_top_tables_capacity: 35,
    allows_host_supplied_alcohol: true,
    corkage_policy: '$15/bottle flat or $250 table unlimited package; allows couple-supplied Cognac/Whiskey with free glassware & ice service',
    asian_banquet_capable: true,
    menu_starting_price_per_table: 720,
    av_stage_included: true,
    score: 98,
    notes: 'Top tier Chinese & Vietnamese banquet chefs, intimate celebration ambience, exceptional live seafood specialties, experienced bilingual banquet staff.',
    contact_email: 'banquets@grandharborevents.com',
    contact_phone: '+1 (626) 280-2998',
    inquiry_email_draft_en: `Subject: Banquet Inquiry for Wedding Celebration (Sep 12, 2026) - Trang & Alfredo\n\nDear Grand Harbor Banquet Director,\n\nWe are hosting our Wedding Celebration on Saturday, September 12, 2026 for approximately 80-100 guests (8 to 10 ten-top round tables). We would like to confirm package pricing for your banquet menu (featuring Lobster, Peking Duck, and Seabass), along with corkage terms for host-supplied Hennessy XO and wine.\n\nPlease provide your banquet pacing schedule, AV/lighting specifications, and deposit requirements.\n\nWarmly,\nTrang & Alfredo`,
    inquiry_email_draft_vi: `Tiêu đề: Đặt Tiệc Cưới Ngày 12/09/2026 - Trang & Alfredo\n\nKính gửi Ban Quản Lý Yến Tiệc Nhà Hàng Grand Harbor,\n\nChúng tôi dự kiến tổ chức Dạ Tiệc Cưới vào Thứ Bảy, 12/09/2026 với quy mô 8 - 10 bàn tiệc tròn 10 người (80 - 100 khách). Xin vui lòng gửi bảng giá chi tiết thực đơn yến tiệc cao cấp (gồm Tôm Hùm, Vịt Quay Bắc Kinh, Cá Chẽm Hấp), kèm chính sách phí phục vụ cho rượu Hennessy XO và rượu vang do gia đình chuẩn bị.\n\nTrân trọng cảm ơn,\nTrang & Alfredo`
  },
  {
    id: 'venue-2',
    name: 'Dragon Palace Imperial Banquet Hall',
    location: 'Garden Grove, CA',
    max_capacity_guests: 400,
    ten_top_tables_capacity: 40,
    allows_host_supplied_alcohol: true,
    corkage_policy: '$20/bottle corkage fee; complimentary champagne toast flute service',
    asian_banquet_capable: true,
    menu_starting_price_per_table: 680,
    av_stage_included: true,
    score: 92,
    notes: 'Famous for authentic seafood banquets, expansive LED backdrop wall, ample parking.',
    contact_email: 'events@dragonpalaceoc.com',
    contact_phone: '+1 (714) 539-9988',
    inquiry_email_draft_en: `Subject: Banquet Availability Inquiry (Sep 12, 2026) - Trang & Alfredo\n\nDear Dragon Palace Team,\n\nWe are planning our 80-person wedding celebration banquet for Sep 12, 2026. We are interested in your 8-course banquet package and bringing our own Cognac bottles for table toasting.\n\nBest regards,\nTrang & Alfredo`,
    inquiry_email_draft_vi: `Tiêu đề: Tư Vấn Tiệc Cưới 12/09/2026 - Trang & Alfredo\n\nKính gửi Dragon Palace Imperial,\n\nChúng tôi muốn tìm hiểu về sảnh tiệc 8-10 bàn 10 người cho tiệc cưới ngày 12/09/2026 và thực đơn yến tiệc hải sản.\n\nTrân trọng,\nTrang & Alfredo`
  },
  {
    id: 'venue-3',
    name: 'The Crown Pavilion & Garden Ballroom',
    location: 'Costa Mesa / Newport Area, CA',
    max_capacity_guests: 250,
    ten_top_tables_capacity: 25,
    allows_host_supplied_alcohol: true,
    corkage_policy: '$30/bottle corkage; licensed outside Asian banquet catering permitted with kitchen prep fee',
    asian_banquet_capable: true,
    menu_starting_price_per_table: 950,
    av_stage_included: false,
    score: 84,
    notes: 'Modern luxury aesthetic with outdoor cocktail garden terrace, higher rental baseline.',
    contact_email: 'weddings@crownpavilionoc.com',
    contact_phone: '+1 (949) 755-1234',
    inquiry_email_draft_en: `Subject: Wedding Reception Inquiry (Sep 12, 2026) - Trang & Alfredo\n\nDear Crown Pavilion Team,\n\nWe are looking to hold our reception on September 12, 2026 for 80-100 guests with outside Vietnamese banquet catering and host-supplied bar service.\n\nWarm regards,\nTrang & Alfredo`,
    inquiry_email_draft_vi: `Tiêu đề: Liên Hệ Thuê Sảnh Tiệc Ngày 12/09/2026 - Trang & Alfredo\n\nKính gửi Ban Quản Lý Crown Pavilion,\n\nChúng tôi quan tâm đến sảnh tiệc cho 80-100 khách với hình thức catering món Á bên ngoài.\n\nTrân trọng,\nTrang & Alfredo`
  }
];
